name: Deploy to Vercel

on:
  push:
    branches:
      - main # Deploy to production on push to main
  pull_request:
    branches:
      - main # Create preview deployment on PR to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Specify your Node.js version

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8 # Specify your pnpm version

      - name: Install dependencies
        working-directory: ./app_code
        run: pnpm install

      - name: Lint check
        working-directory: ./app_code
        run: pnpm run lint

      - name: Run tests
        working-directory: ./app_code
        run: pnpm run test --ci --coverage # Assuming your test script can output to CI

      - name: Build Next.js app
        working-directory: ./app_code
        run: pnpm run build
        env:
          # Pass environment variables required for build if any
          # Example: NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
          # Ensure these are also set in Vercel for runtime
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # Example, if needed for build
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }} # Needed for Sentry webpack plugin
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}

      - name: Security Scan (pnpm audit)
        working-directory: ./app_code
        run: pnpm audit --prod # Check for vulnerabilities in production dependencies

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20 # Or a specific Vercel action like vercel/action
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: ${{ github.ref == 'refs/heads/main' && '--prod' || '' }} # Deploy to production if on main branch
          working-directory: ./app_code 